/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScriptsRouteImport } from './routes/scripts'
import { Route as PlatformsRouteImport } from './routes/platforms'
import { Route as ImagesRouteImport } from './routes/images'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTermsOfServiceRouteImport } from './routes/legal/terms-of-service'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal/privacy-policy'
import { Route as LegalDataDeletionRouteImport } from './routes/legal/data-deletion'
import { Route as ApiOpenapiRouteImport } from './routes/api/openapi'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as OauthYoutubeCallbackRouteImport } from './routes/oauth/youtube/callback'
import { Route as OauthInstagramCallbackRouteImport } from './routes/oauth/instagram/callback'
import { Route as GenerationsJobIdEditRouteImport } from './routes/generations.$jobId.edit'
import { Route as ApiV1ScriptsRouteImport } from './routes/api/v1/scripts'
import { Route as ApiV1PlatformAccountsRouteImport } from './routes/api/v1/platform-accounts'
import { Route as ApiV1ImageAssetsRouteImport } from './routes/api/v1/image-assets'
import { Route as ApiV1GenerationsRouteImport } from './routes/api/v1/generations'
import { Route as ApiV1GenerationProfilesRouteImport } from './routes/api/v1/generation-profiles'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiV1UploadsPresignRouteImport } from './routes/api/v1/uploads/presign'
import { Route as ApiV1ScriptsDraftRouteImport } from './routes/api/v1/scripts/draft'
import { Route as ApiV1ScriptsAnalyzeRouteImport } from './routes/api/v1/scripts/analyze'
import { Route as ApiV1ScriptsScriptIdRouteImport } from './routes/api/v1/scripts/$scriptId'
import { Route as ApiV1PromptsOptimizeRouteImport } from './routes/api/v1/prompts/optimize'
import { Route as ApiV1GenerationsJobIdRouteImport } from './routes/api/v1/generations/$jobId'
import { Route as ApiMediaHubUploadsReferenceImageRouteImport } from './routes/api/media-hub/uploads/reference-image'
import { Route as ApiMediaHubUploadsImageAssetRouteImport } from './routes/api/media-hub/uploads/image-asset'
import { Route as ApiMediaHubImagesAssetIdRouteImport } from './routes/api/media-hub/images/$assetId'
import { Route as ApiV1ScriptsScriptIdGenerateRouteImport } from './routes/api/v1/scripts/$scriptId/generate'
import { Route as ApiV1GenerationsJobIdVideoRouteImport } from './routes/api/v1/generations/$jobId/video'
import { Route as ApiV1GenerationsJobIdRetryRouteImport } from './routes/api/v1/generations/$jobId/retry'
import { Route as ApiV1GenerationsJobIdPublishRouteImport } from './routes/api/v1/generations/$jobId/publish'
import { Route as ApiV1GenerationsJobIdNotifyRouteImport } from './routes/api/v1/generations/$jobId/notify'
import { Route as ApiV1GenerationsJobIdEditsRouteImport } from './routes/api/v1/generations/$jobId/edits'
import { Route as ApiMediaHubGenerationJobIdVideoRouteImport } from './routes/api/media-hub/generation/$jobId/video'
import { Route as ApiV1ScriptsScriptIdShotsShotIdFramesRouteImport } from './routes/api/v1/scripts/$scriptId/shots/$shotId/frames'
import { Route as ApiV1ScriptsScriptIdShotsShotIdCarryFinalFrameRouteImport } from './routes/api/v1/scripts/$scriptId/shots/$shotId/carry-final-frame'
import { Route as ApiV1ScriptsScriptIdShotsShotIdFramesSelectRouteImport } from './routes/api/v1/scripts/$scriptId/shots/$shotId/frames/select'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsRoute = ScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformsRoute = PlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRoute = ImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsOfServiceRoute = LegalTermsOfServiceRouteImport.update({
  id: '/legal/terms-of-service',
  path: '/legal/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/legal/privacy-policy',
  path: '/legal/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDataDeletionRoute = LegalDataDeletionRouteImport.update({
  id: '/legal/data-deletion',
  path: '/legal/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiRoute = ApiOpenapiRouteImport.update({
  id: '/api/openapi',
  path: '/api/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthYoutubeCallbackRoute = OauthYoutubeCallbackRouteImport.update({
  id: '/oauth/youtube/callback',
  path: '/oauth/youtube/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthInstagramCallbackRoute = OauthInstagramCallbackRouteImport.update({
  id: '/oauth/instagram/callback',
  path: '/oauth/instagram/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationsJobIdEditRoute = GenerationsJobIdEditRouteImport.update({
  id: '/generations/$jobId/edit',
  path: '/generations/$jobId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ScriptsRoute = ApiV1ScriptsRouteImport.update({
  id: '/api/v1/scripts',
  path: '/api/v1/scripts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PlatformAccountsRoute = ApiV1PlatformAccountsRouteImport.update({
  id: '/api/v1/platform-accounts',
  path: '/api/v1/platform-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ImageAssetsRoute = ApiV1ImageAssetsRouteImport.update({
  id: '/api/v1/image-assets',
  path: '/api/v1/image-assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1GenerationsRoute = ApiV1GenerationsRouteImport.update({
  id: '/api/v1/generations',
  path: '/api/v1/generations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1GenerationProfilesRoute = ApiV1GenerationProfilesRouteImport.update({
  id: '/api/v1/generation-profiles',
  path: '/api/v1/generation-profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1UploadsPresignRoute = ApiV1UploadsPresignRouteImport.update({
  id: '/api/v1/uploads/presign',
  path: '/api/v1/uploads/presign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ScriptsDraftRoute = ApiV1ScriptsDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => ApiV1ScriptsRoute,
} as any)
const ApiV1ScriptsAnalyzeRoute = ApiV1ScriptsAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => ApiV1ScriptsRoute,
} as any)
const ApiV1ScriptsScriptIdRoute = ApiV1ScriptsScriptIdRouteImport.update({
  id: '/$scriptId',
  path: '/$scriptId',
  getParentRoute: () => ApiV1ScriptsRoute,
} as any)
const ApiV1PromptsOptimizeRoute = ApiV1PromptsOptimizeRouteImport.update({
  id: '/api/v1/prompts/optimize',
  path: '/api/v1/prompts/optimize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1GenerationsJobIdRoute = ApiV1GenerationsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => ApiV1GenerationsRoute,
} as any)
const ApiMediaHubUploadsReferenceImageRoute =
  ApiMediaHubUploadsReferenceImageRouteImport.update({
    id: '/api/media-hub/uploads/reference-image',
    path: '/api/media-hub/uploads/reference-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMediaHubUploadsImageAssetRoute =
  ApiMediaHubUploadsImageAssetRouteImport.update({
    id: '/api/media-hub/uploads/image-asset',
    path: '/api/media-hub/uploads/image-asset',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMediaHubImagesAssetIdRoute =
  ApiMediaHubImagesAssetIdRouteImport.update({
    id: '/api/media-hub/images/$assetId',
    path: '/api/media-hub/images/$assetId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ScriptsScriptIdGenerateRoute =
  ApiV1ScriptsScriptIdGenerateRouteImport.update({
    id: '/generate',
    path: '/generate',
    getParentRoute: () => ApiV1ScriptsScriptIdRoute,
  } as any)
const ApiV1GenerationsJobIdVideoRoute =
  ApiV1GenerationsJobIdVideoRouteImport.update({
    id: '/video',
    path: '/video',
    getParentRoute: () => ApiV1GenerationsJobIdRoute,
  } as any)
const ApiV1GenerationsJobIdRetryRoute =
  ApiV1GenerationsJobIdRetryRouteImport.update({
    id: '/retry',
    path: '/retry',
    getParentRoute: () => ApiV1GenerationsJobIdRoute,
  } as any)
const ApiV1GenerationsJobIdPublishRoute =
  ApiV1GenerationsJobIdPublishRouteImport.update({
    id: '/publish',
    path: '/publish',
    getParentRoute: () => ApiV1GenerationsJobIdRoute,
  } as any)
const ApiV1GenerationsJobIdNotifyRoute =
  ApiV1GenerationsJobIdNotifyRouteImport.update({
    id: '/notify',
    path: '/notify',
    getParentRoute: () => ApiV1GenerationsJobIdRoute,
  } as any)
const ApiV1GenerationsJobIdEditsRoute =
  ApiV1GenerationsJobIdEditsRouteImport.update({
    id: '/edits',
    path: '/edits',
    getParentRoute: () => ApiV1GenerationsJobIdRoute,
  } as any)
const ApiMediaHubGenerationJobIdVideoRoute =
  ApiMediaHubGenerationJobIdVideoRouteImport.update({
    id: '/api/media-hub/generation/$jobId/video',
    path: '/api/media-hub/generation/$jobId/video',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ScriptsScriptIdShotsShotIdFramesRoute =
  ApiV1ScriptsScriptIdShotsShotIdFramesRouteImport.update({
    id: '/shots/$shotId/frames',
    path: '/shots/$shotId/frames',
    getParentRoute: () => ApiV1ScriptsScriptIdRoute,
  } as any)
const ApiV1ScriptsScriptIdShotsShotIdCarryFinalFrameRoute =
  ApiV1ScriptsScriptIdShotsShotIdCarryFinalFrameRouteImport.update({
    id: '/shots/$shotId/carry-final-frame',
    path: '/shots/$shotId/carry-final-frame',
    getParentRoute: () => ApiV1ScriptsScriptIdRoute,
  } as any)
const ApiV1ScriptsScriptIdShotsShotIdFramesSelectRoute =
  ApiV1ScriptsScriptIdShotsShotIdFramesSelectRouteImport.update({
    id: '/select',
    path: '/select',
    getParentRoute: () => ApiV1ScriptsScriptIdShotsShotIdFramesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/images': typeof ImagesRoute
  '/platforms': typeof PlatformsRoute
  '/scripts': typeof ScriptsRoute
  '/settings': typeof SettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/legal/data-deletion': typeof LegalDataDeletionRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/v1/generation-profiles': typeof ApiV1GenerationProfilesRoute
  '/api/v1/generations': typeof ApiV1GenerationsRouteWithChildren
  '/api/v1/image-assets': typeof ApiV1ImageAssetsRoute
  '/api/v1/platform-accounts': typeof ApiV1PlatformAccountsRoute
  '/api/v1/scripts': typeof ApiV1ScriptsRouteWithChildren
  '/generations/$jobId/edit': typeof GenerationsJobIdEditRoute
  '/oauth/instagram/callback': typeof OauthInstagramCallbackRoute
  '/oauth/youtube/callback': typeof OauthYoutubeCallbackRoute
  '/api/media-hub/images/$assetId': typeof ApiMediaHubImagesAssetIdRoute
  '/api/media-hub/uploads/image-asset': typeof ApiMediaHubUploadsImageAssetRoute
  '/api/media-hub/uploads/reference-image': typeof ApiMediaHubUploadsReferenceImageRoute
  '/api/v1/generations/$jobId': typeof ApiV1GenerationsJobIdRouteWithChildren
  '/api/v1/prompts/optimize': typeof ApiV1PromptsOptimizeRoute
  '/api/v1/scripts/$scriptId': typeof ApiV1ScriptsScriptIdRouteWithChildren
  '/api/v1/scripts/analyze': typeof ApiV1ScriptsAnalyzeRoute
  '/api/v1/scripts/draft': typeof ApiV1ScriptsDraftRoute
  '/api/v1/uploads/presign': typeof ApiV1UploadsPresignRoute
  '/api/media-hub/generation/$jobId/video': typeof ApiMediaHubGenerationJobIdVideoRoute
  '/api/v1/generations/$jobId/edits': typeof ApiV1GenerationsJobIdEditsRoute
  '/api/v1/generations/$jobId/notify': typeof ApiV1GenerationsJobIdNotifyRoute
  '/api/v1/generations/$jobId/publish': typeof ApiV1GenerationsJobIdPublishRoute
  '/api/v1/generations/$jobId/retry': typeof ApiV1GenerationsJobIdRetryRoute
  '/api/v1/generations/$jobId/video': typeof ApiV1GenerationsJobIdVideoRoute
  '/api/v1/scripts/$scriptId/generate': typeof ApiV1ScriptsScriptIdGenerateRoute
  '/api/v1/scripts/$scriptId/shots/$shotId/carry-final-frame': typeof ApiV1ScriptsScriptIdShotsShotIdCarryFinalFrameRoute
  '/api/v1/scripts/$scriptId/shots/$shotId/frames': typeof ApiV1ScriptsScriptIdShotsShotIdFramesRouteWithChildren
  '/api/v1/scripts/$scriptId/shots/$shotId/frames/select': typeof ApiV1ScriptsScriptIdShotsShotIdFramesSelectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/images': typeof ImagesRoute
  '/platforms': typeof PlatformsRoute
  '/scripts': typeof ScriptsRoute
  '/settings': typeof SettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/legal/data-deletion': typeof LegalDataDeletionRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/v1/generation-profiles': typeof ApiV1GenerationProfilesRoute
  '/api/v1/generations': typeof ApiV1GenerationsRouteWithChildren
  '/api/v1/image-assets': typeof ApiV1ImageAssetsRoute
  '/api/v1/platform-accounts': typeof ApiV1PlatformAccountsRoute
  '/api/v1/scripts': typeof ApiV1ScriptsRouteWithChildren
  '/generations/$jobId/edit': typeof GenerationsJobIdEditRoute
  '/oauth/instagram/callback': typeof OauthInstagramCallbackRoute
  '/oauth/youtube/callback': typeof OauthYoutubeCallbackRoute
  '/api/media-hub/images/$assetId': typeof ApiMediaHubImagesAssetIdRoute
  '/api/media-hub/uploads/image-asset': typeof ApiMediaHubUploadsImageAssetRoute
  '/api/media-hub/uploads/reference-image': typeof ApiMediaHubUploadsReferenceImageRoute
  '/api/v1/generations/$jobId': typeof ApiV1GenerationsJobIdRouteWithChildren
  '/api/v1/prompts/optimize': typeof ApiV1PromptsOptimizeRoute
  '/api/v1/scripts/$scriptId': typeof ApiV1ScriptsScriptIdRouteWithChildren
  '/api/v1/scripts/analyze': typeof ApiV1ScriptsAnalyzeRoute
  '/api/v1/scripts/draft': typeof ApiV1ScriptsDraftRoute
  '/api/v1/uploads/presign': typeof ApiV1UploadsPresignRoute
  '/api/media-hub/generation/$jobId/video': typeof ApiMediaHubGenerationJobIdVideoRoute
  '/api/v1/generations/$jobId/edits': typeof ApiV1GenerationsJobIdEditsRoute
  '/api/v1/generations/$jobId/notify': typeof ApiV1GenerationsJobIdNotifyRoute
  '/api/v1/generations/$jobId/publish': typeof ApiV1GenerationsJobIdPublishRoute
  '/api/v1/generations/$jobId/retry': typeof ApiV1GenerationsJobIdRetryRoute
  '/api/v1/generations/$jobId/video': typeof ApiV1GenerationsJobIdVideoRoute
  '/api/v1/scripts/$scriptId/generate': typeof ApiV1ScriptsScriptIdGenerateRoute
  '/api/v1/scripts/$scriptId/shots/$shotId/carry-final-frame': typeof ApiV1ScriptsScriptIdShotsShotIdCarryFinalFrameRoute
  '/api/v1/scripts/$scriptId/shots/$shotId/frames': typeof ApiV1ScriptsScriptIdShotsShotIdFramesRouteWithChildren
  '/api/v1/scripts/$scriptId/shots/$shotId/frames/select': typeof ApiV1ScriptsScriptIdShotsShotIdFramesSelectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/images': typeof ImagesRoute
  '/platforms': typeof PlatformsRoute
  '/scripts': typeof ScriptsRoute
  '/settings': typeof SettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/legal/data-deletion': typeof LegalDataDeletionRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/v1/generation-profiles': typeof ApiV1GenerationProfilesRoute
  '/api/v1/generations': typeof ApiV1GenerationsRouteWithChildren
  '/api/v1/image-assets': typeof ApiV1ImageAssetsRoute
  '/api/v1/platform-accounts': typeof ApiV1PlatformAccountsRoute
  '/api/v1/scripts': typeof ApiV1ScriptsRouteWithChildren
  '/generations/$jobId/edit': typeof GenerationsJobIdEditRoute
  '/oauth/instagram/callback': typeof OauthInstagramCallbackRoute
  '/oauth/youtube/callback': typeof OauthYoutubeCallbackRoute
  '/api/media-hub/images/$assetId': typeof ApiMediaHubImagesAssetIdRoute
  '/api/media-hub/uploads/image-asset': typeof ApiMediaHubUploadsImageAssetRoute
  '/api/media-hub/uploads/reference-image': typeof ApiMediaHubUploadsReferenceImageRoute
  '/api/v1/generations/$jobId': typeof ApiV1GenerationsJobIdRouteWithChildren
  '/api/v1/prompts/optimize': typeof ApiV1PromptsOptimizeRoute
  '/api/v1/scripts/$scriptId': typeof ApiV1ScriptsScriptIdRouteWithChildren
  '/api/v1/scripts/analyze': typeof ApiV1ScriptsAnalyzeRoute
  '/api/v1/scripts/draft': typeof ApiV1ScriptsDraftRoute
  '/api/v1/uploads/presign': typeof ApiV1UploadsPresignRoute
  '/api/media-hub/generation/$jobId/video': typeof ApiMediaHubGenerationJobIdVideoRoute
  '/api/v1/generations/$jobId/edits': typeof ApiV1GenerationsJobIdEditsRoute
  '/api/v1/generations/$jobId/notify': typeof ApiV1GenerationsJobIdNotifyRoute
  '/api/v1/generations/$jobId/publish': typeof ApiV1GenerationsJobIdPublishRoute
  '/api/v1/generations/$jobId/retry': typeof ApiV1GenerationsJobIdRetryRoute
  '/api/v1/generations/$jobId/video': typeof ApiV1GenerationsJobIdVideoRoute
  '/api/v1/scripts/$scriptId/generate': typeof ApiV1ScriptsScriptIdGenerateRoute
  '/api/v1/scripts/$scriptId/shots/$shotId/carry-final-frame': typeof ApiV1ScriptsScriptIdShotsShotIdCarryFinalFrameRoute
  '/api/v1/scripts/$scriptId/shots/$shotId/frames': typeof ApiV1ScriptsScriptIdShotsShotIdFramesRouteWithChildren
  '/api/v1/scripts/$scriptId/shots/$shotId/frames/select': typeof ApiV1ScriptsScriptIdShotsShotIdFramesSelectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/images'
    | '/platforms'
    | '/scripts'
    | '/settings'
    | '/admin/users'
    | '/api/health'
    | '/api/openapi'
    | '/legal/data-deletion'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/v1/generation-profiles'
    | '/api/v1/generations'
    | '/api/v1/image-assets'
    | '/api/v1/platform-accounts'
    | '/api/v1/scripts'
    | '/generations/$jobId/edit'
    | '/oauth/instagram/callback'
    | '/oauth/youtube/callback'
    | '/api/media-hub/images/$assetId'
    | '/api/media-hub/uploads/image-asset'
    | '/api/media-hub/uploads/reference-image'
    | '/api/v1/generations/$jobId'
    | '/api/v1/prompts/optimize'
    | '/api/v1/scripts/$scriptId'
    | '/api/v1/scripts/analyze'
    | '/api/v1/scripts/draft'
    | '/api/v1/uploads/presign'
    | '/api/media-hub/generation/$jobId/video'
    | '/api/v1/generations/$jobId/edits'
    | '/api/v1/generations/$jobId/notify'
    | '/api/v1/generations/$jobId/publish'
    | '/api/v1/generations/$jobId/retry'
    | '/api/v1/generations/$jobId/video'
    | '/api/v1/scripts/$scriptId/generate'
    | '/api/v1/scripts/$scriptId/shots/$shotId/carry-final-frame'
    | '/api/v1/scripts/$scriptId/shots/$shotId/frames'
    | '/api/v1/scripts/$scriptId/shots/$shotId/frames/select'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/images'
    | '/platforms'
    | '/scripts'
    | '/settings'
    | '/admin/users'
    | '/api/health'
    | '/api/openapi'
    | '/legal/data-deletion'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/v1/generation-profiles'
    | '/api/v1/generations'
    | '/api/v1/image-assets'
    | '/api/v1/platform-accounts'
    | '/api/v1/scripts'
    | '/generations/$jobId/edit'
    | '/oauth/instagram/callback'
    | '/oauth/youtube/callback'
    | '/api/media-hub/images/$assetId'
    | '/api/media-hub/uploads/image-asset'
    | '/api/media-hub/uploads/reference-image'
    | '/api/v1/generations/$jobId'
    | '/api/v1/prompts/optimize'
    | '/api/v1/scripts/$scriptId'
    | '/api/v1/scripts/analyze'
    | '/api/v1/scripts/draft'
    | '/api/v1/uploads/presign'
    | '/api/media-hub/generation/$jobId/video'
    | '/api/v1/generations/$jobId/edits'
    | '/api/v1/generations/$jobId/notify'
    | '/api/v1/generations/$jobId/publish'
    | '/api/v1/generations/$jobId/retry'
    | '/api/v1/generations/$jobId/video'
    | '/api/v1/scripts/$scriptId/generate'
    | '/api/v1/scripts/$scriptId/shots/$shotId/carry-final-frame'
    | '/api/v1/scripts/$scriptId/shots/$shotId/frames'
    | '/api/v1/scripts/$scriptId/shots/$shotId/frames/select'
  id:
    | '__root__'
    | '/'
    | '/images'
    | '/platforms'
    | '/scripts'
    | '/settings'
    | '/admin/users'
    | '/api/health'
    | '/api/openapi'
    | '/legal/data-deletion'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/v1/generation-profiles'
    | '/api/v1/generations'
    | '/api/v1/image-assets'
    | '/api/v1/platform-accounts'
    | '/api/v1/scripts'
    | '/generations/$jobId/edit'
    | '/oauth/instagram/callback'
    | '/oauth/youtube/callback'
    | '/api/media-hub/images/$assetId'
    | '/api/media-hub/uploads/image-asset'
    | '/api/media-hub/uploads/reference-image'
    | '/api/v1/generations/$jobId'
    | '/api/v1/prompts/optimize'
    | '/api/v1/scripts/$scriptId'
    | '/api/v1/scripts/analyze'
    | '/api/v1/scripts/draft'
    | '/api/v1/uploads/presign'
    | '/api/media-hub/generation/$jobId/video'
    | '/api/v1/generations/$jobId/edits'
    | '/api/v1/generations/$jobId/notify'
    | '/api/v1/generations/$jobId/publish'
    | '/api/v1/generations/$jobId/retry'
    | '/api/v1/generations/$jobId/video'
    | '/api/v1/scripts/$scriptId/generate'
    | '/api/v1/scripts/$scriptId/shots/$shotId/carry-final-frame'
    | '/api/v1/scripts/$scriptId/shots/$shotId/frames'
    | '/api/v1/scripts/$scriptId/shots/$shotId/frames/select'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImagesRoute: typeof ImagesRoute
  PlatformsRoute: typeof PlatformsRoute
  ScriptsRoute: typeof ScriptsRoute
  SettingsRoute: typeof SettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiOpenapiRoute: typeof ApiOpenapiRoute
  LegalDataDeletionRoute: typeof LegalDataDeletionRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalTermsOfServiceRoute: typeof LegalTermsOfServiceRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiV1GenerationProfilesRoute: typeof ApiV1GenerationProfilesRoute
  ApiV1GenerationsRoute: typeof ApiV1GenerationsRouteWithChildren
  ApiV1ImageAssetsRoute: typeof ApiV1ImageAssetsRoute
  ApiV1PlatformAccountsRoute: typeof ApiV1PlatformAccountsRoute
  ApiV1ScriptsRoute: typeof ApiV1ScriptsRouteWithChildren
  GenerationsJobIdEditRoute: typeof GenerationsJobIdEditRoute
  OauthInstagramCallbackRoute: typeof OauthInstagramCallbackRoute
  OauthYoutubeCallbackRoute: typeof OauthYoutubeCallbackRoute
  ApiMediaHubImagesAssetIdRoute: typeof ApiMediaHubImagesAssetIdRoute
  ApiMediaHubUploadsImageAssetRoute: typeof ApiMediaHubUploadsImageAssetRoute
  ApiMediaHubUploadsReferenceImageRoute: typeof ApiMediaHubUploadsReferenceImageRoute
  ApiV1PromptsOptimizeRoute: typeof ApiV1PromptsOptimizeRoute
  ApiV1UploadsPresignRoute: typeof ApiV1UploadsPresignRoute
  ApiMediaHubGenerationJobIdVideoRoute: typeof ApiMediaHubGenerationJobIdVideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts': {
      id: '/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof ScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platforms': {
      id: '/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof PlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms-of-service': {
      id: '/legal/terms-of-service'
      path: '/legal/terms-of-service'
      fullPath: '/legal/terms-of-service'
      preLoaderRoute: typeof LegalTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/data-deletion': {
      id: '/legal/data-deletion'
      path: '/legal/data-deletion'
      fullPath: '/legal/data-deletion'
      preLoaderRoute: typeof LegalDataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi': {
      id: '/api/openapi'
      path: '/api/openapi'
      fullPath: '/api/openapi'
      preLoaderRoute: typeof ApiOpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/youtube/callback': {
      id: '/oauth/youtube/callback'
      path: '/oauth/youtube/callback'
      fullPath: '/oauth/youtube/callback'
      preLoaderRoute: typeof OauthYoutubeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/instagram/callback': {
      id: '/oauth/instagram/callback'
      path: '/oauth/instagram/callback'
      fullPath: '/oauth/instagram/callback'
      preLoaderRoute: typeof OauthInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generations/$jobId/edit': {
      id: '/generations/$jobId/edit'
      path: '/generations/$jobId/edit'
      fullPath: '/generations/$jobId/edit'
      preLoaderRoute: typeof GenerationsJobIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/scripts': {
      id: '/api/v1/scripts'
      path: '/api/v1/scripts'
      fullPath: '/api/v1/scripts'
      preLoaderRoute: typeof ApiV1ScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/platform-accounts': {
      id: '/api/v1/platform-accounts'
      path: '/api/v1/platform-accounts'
      fullPath: '/api/v1/platform-accounts'
      preLoaderRoute: typeof ApiV1PlatformAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/image-assets': {
      id: '/api/v1/image-assets'
      path: '/api/v1/image-assets'
      fullPath: '/api/v1/image-assets'
      preLoaderRoute: typeof ApiV1ImageAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/generations': {
      id: '/api/v1/generations'
      path: '/api/v1/generations'
      fullPath: '/api/v1/generations'
      preLoaderRoute: typeof ApiV1GenerationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/generation-profiles': {
      id: '/api/v1/generation-profiles'
      path: '/api/v1/generation-profiles'
      fullPath: '/api/v1/generation-profiles'
      preLoaderRoute: typeof ApiV1GenerationProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/uploads/presign': {
      id: '/api/v1/uploads/presign'
      path: '/api/v1/uploads/presign'
      fullPath: '/api/v1/uploads/presign'
      preLoaderRoute: typeof ApiV1UploadsPresignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/scripts/draft': {
      id: '/api/v1/scripts/draft'
      path: '/draft'
      fullPath: '/api/v1/scripts/draft'
      preLoaderRoute: typeof ApiV1ScriptsDraftRouteImport
      parentRoute: typeof ApiV1ScriptsRoute
    }
    '/api/v1/scripts/analyze': {
      id: '/api/v1/scripts/analyze'
      path: '/analyze'
      fullPath: '/api/v1/scripts/analyze'
      preLoaderRoute: typeof ApiV1ScriptsAnalyzeRouteImport
      parentRoute: typeof ApiV1ScriptsRoute
    }
    '/api/v1/scripts/$scriptId': {
      id: '/api/v1/scripts/$scriptId'
      path: '/$scriptId'
      fullPath: '/api/v1/scripts/$scriptId'
      preLoaderRoute: typeof ApiV1ScriptsScriptIdRouteImport
      parentRoute: typeof ApiV1ScriptsRoute
    }
    '/api/v1/prompts/optimize': {
      id: '/api/v1/prompts/optimize'
      path: '/api/v1/prompts/optimize'
      fullPath: '/api/v1/prompts/optimize'
      preLoaderRoute: typeof ApiV1PromptsOptimizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/generations/$jobId': {
      id: '/api/v1/generations/$jobId'
      path: '/$jobId'
      fullPath: '/api/v1/generations/$jobId'
      preLoaderRoute: typeof ApiV1GenerationsJobIdRouteImport
      parentRoute: typeof ApiV1GenerationsRoute
    }
    '/api/media-hub/uploads/reference-image': {
      id: '/api/media-hub/uploads/reference-image'
      path: '/api/media-hub/uploads/reference-image'
      fullPath: '/api/media-hub/uploads/reference-image'
      preLoaderRoute: typeof ApiMediaHubUploadsReferenceImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media-hub/uploads/image-asset': {
      id: '/api/media-hub/uploads/image-asset'
      path: '/api/media-hub/uploads/image-asset'
      fullPath: '/api/media-hub/uploads/image-asset'
      preLoaderRoute: typeof ApiMediaHubUploadsImageAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media-hub/images/$assetId': {
      id: '/api/media-hub/images/$assetId'
      path: '/api/media-hub/images/$assetId'
      fullPath: '/api/media-hub/images/$assetId'
      preLoaderRoute: typeof ApiMediaHubImagesAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/scripts/$scriptId/generate': {
      id: '/api/v1/scripts/$scriptId/generate'
      path: '/generate'
      fullPath: '/api/v1/scripts/$scriptId/generate'
      preLoaderRoute: typeof ApiV1ScriptsScriptIdGenerateRouteImport
      parentRoute: typeof ApiV1ScriptsScriptIdRoute
    }
    '/api/v1/generations/$jobId/video': {
      id: '/api/v1/generations/$jobId/video'
      path: '/video'
      fullPath: '/api/v1/generations/$jobId/video'
      preLoaderRoute: typeof ApiV1GenerationsJobIdVideoRouteImport
      parentRoute: typeof ApiV1GenerationsJobIdRoute
    }
    '/api/v1/generations/$jobId/retry': {
      id: '/api/v1/generations/$jobId/retry'
      path: '/retry'
      fullPath: '/api/v1/generations/$jobId/retry'
      preLoaderRoute: typeof ApiV1GenerationsJobIdRetryRouteImport
      parentRoute: typeof ApiV1GenerationsJobIdRoute
    }
    '/api/v1/generations/$jobId/publish': {
      id: '/api/v1/generations/$jobId/publish'
      path: '/publish'
      fullPath: '/api/v1/generations/$jobId/publish'
      preLoaderRoute: typeof ApiV1GenerationsJobIdPublishRouteImport
      parentRoute: typeof ApiV1GenerationsJobIdRoute
    }
    '/api/v1/generations/$jobId/notify': {
      id: '/api/v1/generations/$jobId/notify'
      path: '/notify'
      fullPath: '/api/v1/generations/$jobId/notify'
      preLoaderRoute: typeof ApiV1GenerationsJobIdNotifyRouteImport
      parentRoute: typeof ApiV1GenerationsJobIdRoute
    }
    '/api/v1/generations/$jobId/edits': {
      id: '/api/v1/generations/$jobId/edits'
      path: '/edits'
      fullPath: '/api/v1/generations/$jobId/edits'
      preLoaderRoute: typeof ApiV1GenerationsJobIdEditsRouteImport
      parentRoute: typeof ApiV1GenerationsJobIdRoute
    }
    '/api/media-hub/generation/$jobId/video': {
      id: '/api/media-hub/generation/$jobId/video'
      path: '/api/media-hub/generation/$jobId/video'
      fullPath: '/api/media-hub/generation/$jobId/video'
      preLoaderRoute: typeof ApiMediaHubGenerationJobIdVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/scripts/$scriptId/shots/$shotId/frames': {
      id: '/api/v1/scripts/$scriptId/shots/$shotId/frames'
      path: '/shots/$shotId/frames'
      fullPath: '/api/v1/scripts/$scriptId/shots/$shotId/frames'
      preLoaderRoute: typeof ApiV1ScriptsScriptIdShotsShotIdFramesRouteImport
      parentRoute: typeof ApiV1ScriptsScriptIdRoute
    }
    '/api/v1/scripts/$scriptId/shots/$shotId/carry-final-frame': {
      id: '/api/v1/scripts/$scriptId/shots/$shotId/carry-final-frame'
      path: '/shots/$shotId/carry-final-frame'
      fullPath: '/api/v1/scripts/$scriptId/shots/$shotId/carry-final-frame'
      preLoaderRoute: typeof ApiV1ScriptsScriptIdShotsShotIdCarryFinalFrameRouteImport
      parentRoute: typeof ApiV1ScriptsScriptIdRoute
    }
    '/api/v1/scripts/$scriptId/shots/$shotId/frames/select': {
      id: '/api/v1/scripts/$scriptId/shots/$shotId/frames/select'
      path: '/select'
      fullPath: '/api/v1/scripts/$scriptId/shots/$shotId/frames/select'
      preLoaderRoute: typeof ApiV1ScriptsScriptIdShotsShotIdFramesSelectRouteImport
      parentRoute: typeof ApiV1ScriptsScriptIdShotsShotIdFramesRoute
    }
  }
}

interface ApiV1GenerationsJobIdRouteChildren {
  ApiV1GenerationsJobIdEditsRoute: typeof ApiV1GenerationsJobIdEditsRoute
  ApiV1GenerationsJobIdNotifyRoute: typeof ApiV1GenerationsJobIdNotifyRoute
  ApiV1GenerationsJobIdPublishRoute: typeof ApiV1GenerationsJobIdPublishRoute
  ApiV1GenerationsJobIdRetryRoute: typeof ApiV1GenerationsJobIdRetryRoute
  ApiV1GenerationsJobIdVideoRoute: typeof ApiV1GenerationsJobIdVideoRoute
}

const ApiV1GenerationsJobIdRouteChildren: ApiV1GenerationsJobIdRouteChildren = {
  ApiV1GenerationsJobIdEditsRoute: ApiV1GenerationsJobIdEditsRoute,
  ApiV1GenerationsJobIdNotifyRoute: ApiV1GenerationsJobIdNotifyRoute,
  ApiV1GenerationsJobIdPublishRoute: ApiV1GenerationsJobIdPublishRoute,
  ApiV1GenerationsJobIdRetryRoute: ApiV1GenerationsJobIdRetryRoute,
  ApiV1GenerationsJobIdVideoRoute: ApiV1GenerationsJobIdVideoRoute,
}

const ApiV1GenerationsJobIdRouteWithChildren =
  ApiV1GenerationsJobIdRoute._addFileChildren(
    ApiV1GenerationsJobIdRouteChildren,
  )

interface ApiV1GenerationsRouteChildren {
  ApiV1GenerationsJobIdRoute: typeof ApiV1GenerationsJobIdRouteWithChildren
}

const ApiV1GenerationsRouteChildren: ApiV1GenerationsRouteChildren = {
  ApiV1GenerationsJobIdRoute: ApiV1GenerationsJobIdRouteWithChildren,
}

const ApiV1GenerationsRouteWithChildren =
  ApiV1GenerationsRoute._addFileChildren(ApiV1GenerationsRouteChildren)

interface ApiV1ScriptsScriptIdShotsShotIdFramesRouteChildren {
  ApiV1ScriptsScriptIdShotsShotIdFramesSelectRoute: typeof ApiV1ScriptsScriptIdShotsShotIdFramesSelectRoute
}

const ApiV1ScriptsScriptIdShotsShotIdFramesRouteChildren: ApiV1ScriptsScriptIdShotsShotIdFramesRouteChildren =
  {
    ApiV1ScriptsScriptIdShotsShotIdFramesSelectRoute:
      ApiV1ScriptsScriptIdShotsShotIdFramesSelectRoute,
  }

const ApiV1ScriptsScriptIdShotsShotIdFramesRouteWithChildren =
  ApiV1ScriptsScriptIdShotsShotIdFramesRoute._addFileChildren(
    ApiV1ScriptsScriptIdShotsShotIdFramesRouteChildren,
  )

interface ApiV1ScriptsScriptIdRouteChildren {
  ApiV1ScriptsScriptIdGenerateRoute: typeof ApiV1ScriptsScriptIdGenerateRoute
  ApiV1ScriptsScriptIdShotsShotIdCarryFinalFrameRoute: typeof ApiV1ScriptsScriptIdShotsShotIdCarryFinalFrameRoute
  ApiV1ScriptsScriptIdShotsShotIdFramesRoute: typeof ApiV1ScriptsScriptIdShotsShotIdFramesRouteWithChildren
}

const ApiV1ScriptsScriptIdRouteChildren: ApiV1ScriptsScriptIdRouteChildren = {
  ApiV1ScriptsScriptIdGenerateRoute: ApiV1ScriptsScriptIdGenerateRoute,
  ApiV1ScriptsScriptIdShotsShotIdCarryFinalFrameRoute:
    ApiV1ScriptsScriptIdShotsShotIdCarryFinalFrameRoute,
  ApiV1ScriptsScriptIdShotsShotIdFramesRoute:
    ApiV1ScriptsScriptIdShotsShotIdFramesRouteWithChildren,
}

const ApiV1ScriptsScriptIdRouteWithChildren =
  ApiV1ScriptsScriptIdRoute._addFileChildren(ApiV1ScriptsScriptIdRouteChildren)

interface ApiV1ScriptsRouteChildren {
  ApiV1ScriptsScriptIdRoute: typeof ApiV1ScriptsScriptIdRouteWithChildren
  ApiV1ScriptsAnalyzeRoute: typeof ApiV1ScriptsAnalyzeRoute
  ApiV1ScriptsDraftRoute: typeof ApiV1ScriptsDraftRoute
}

const ApiV1ScriptsRouteChildren: ApiV1ScriptsRouteChildren = {
  ApiV1ScriptsScriptIdRoute: ApiV1ScriptsScriptIdRouteWithChildren,
  ApiV1ScriptsAnalyzeRoute: ApiV1ScriptsAnalyzeRoute,
  ApiV1ScriptsDraftRoute: ApiV1ScriptsDraftRoute,
}

const ApiV1ScriptsRouteWithChildren = ApiV1ScriptsRoute._addFileChildren(
  ApiV1ScriptsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImagesRoute: ImagesRoute,
  PlatformsRoute: PlatformsRoute,
  ScriptsRoute: ScriptsRoute,
  SettingsRoute: SettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiOpenapiRoute: ApiOpenapiRoute,
  LegalDataDeletionRoute: LegalDataDeletionRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalTermsOfServiceRoute: LegalTermsOfServiceRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiV1GenerationProfilesRoute: ApiV1GenerationProfilesRoute,
  ApiV1GenerationsRoute: ApiV1GenerationsRouteWithChildren,
  ApiV1ImageAssetsRoute: ApiV1ImageAssetsRoute,
  ApiV1PlatformAccountsRoute: ApiV1PlatformAccountsRoute,
  ApiV1ScriptsRoute: ApiV1ScriptsRouteWithChildren,
  GenerationsJobIdEditRoute: GenerationsJobIdEditRoute,
  OauthInstagramCallbackRoute: OauthInstagramCallbackRoute,
  OauthYoutubeCallbackRoute: OauthYoutubeCallbackRoute,
  ApiMediaHubImagesAssetIdRoute: ApiMediaHubImagesAssetIdRoute,
  ApiMediaHubUploadsImageAssetRoute: ApiMediaHubUploadsImageAssetRoute,
  ApiMediaHubUploadsReferenceImageRoute: ApiMediaHubUploadsReferenceImageRoute,
  ApiV1PromptsOptimizeRoute: ApiV1PromptsOptimizeRoute,
  ApiV1UploadsPresignRoute: ApiV1UploadsPresignRoute,
  ApiMediaHubGenerationJobIdVideoRoute: ApiMediaHubGenerationJobIdVideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
