/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTermsOfServiceRouteImport } from './routes/legal/terms-of-service'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal/privacy-policy'
import { Route as LegalDataDeletionRouteImport } from './routes/legal/data-deletion'
import { Route as ApiOpenapiRouteImport } from './routes/api/openapi'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as OauthYoutubeCallbackRouteImport } from './routes/oauth/youtube/callback'
import { Route as OauthInstagramCallbackRouteImport } from './routes/oauth/instagram/callback'
import { Route as GenerationsJobIdEditRouteImport } from './routes/generations.$jobId.edit'
import { Route as ApiV1PlatformAccountsRouteImport } from './routes/api/v1/platform-accounts'
import { Route as ApiV1GenerationsRouteImport } from './routes/api/v1/generations'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiV1UploadsPresignRouteImport } from './routes/api/v1/uploads/presign'
import { Route as ApiV1PromptsOptimizeRouteImport } from './routes/api/v1/prompts/optimize'
import { Route as ApiV1GenerationsJobIdRouteImport } from './routes/api/v1/generations/$jobId'
import { Route as ApiMediaHubUploadsReferenceImageRouteImport } from './routes/api/media-hub/uploads/reference-image'
import { Route as ApiV1GenerationsJobIdVideoRouteImport } from './routes/api/v1/generations/$jobId/video'
import { Route as ApiV1GenerationsJobIdRetryRouteImport } from './routes/api/v1/generations/$jobId/retry'
import { Route as ApiV1GenerationsJobIdPublishRouteImport } from './routes/api/v1/generations/$jobId/publish'
import { Route as ApiV1GenerationsJobIdNotifyRouteImport } from './routes/api/v1/generations/$jobId/notify'
import { Route as ApiV1GenerationsJobIdEditsRouteImport } from './routes/api/v1/generations/$jobId/edits'
import { Route as ApiMediaHubGenerationJobIdVideoRouteImport } from './routes/api/media-hub/generation/$jobId/video'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsOfServiceRoute = LegalTermsOfServiceRouteImport.update({
  id: '/legal/terms-of-service',
  path: '/legal/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/legal/privacy-policy',
  path: '/legal/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDataDeletionRoute = LegalDataDeletionRouteImport.update({
  id: '/legal/data-deletion',
  path: '/legal/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiRoute = ApiOpenapiRouteImport.update({
  id: '/api/openapi',
  path: '/api/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthYoutubeCallbackRoute = OauthYoutubeCallbackRouteImport.update({
  id: '/oauth/youtube/callback',
  path: '/oauth/youtube/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthInstagramCallbackRoute = OauthInstagramCallbackRouteImport.update({
  id: '/oauth/instagram/callback',
  path: '/oauth/instagram/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationsJobIdEditRoute = GenerationsJobIdEditRouteImport.update({
  id: '/generations/$jobId/edit',
  path: '/generations/$jobId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PlatformAccountsRoute = ApiV1PlatformAccountsRouteImport.update({
  id: '/api/v1/platform-accounts',
  path: '/api/v1/platform-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1GenerationsRoute = ApiV1GenerationsRouteImport.update({
  id: '/api/v1/generations',
  path: '/api/v1/generations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1UploadsPresignRoute = ApiV1UploadsPresignRouteImport.update({
  id: '/api/v1/uploads/presign',
  path: '/api/v1/uploads/presign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PromptsOptimizeRoute = ApiV1PromptsOptimizeRouteImport.update({
  id: '/api/v1/prompts/optimize',
  path: '/api/v1/prompts/optimize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1GenerationsJobIdRoute = ApiV1GenerationsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => ApiV1GenerationsRoute,
} as any)
const ApiMediaHubUploadsReferenceImageRoute =
  ApiMediaHubUploadsReferenceImageRouteImport.update({
    id: '/api/media-hub/uploads/reference-image',
    path: '/api/media-hub/uploads/reference-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1GenerationsJobIdVideoRoute =
  ApiV1GenerationsJobIdVideoRouteImport.update({
    id: '/video',
    path: '/video',
    getParentRoute: () => ApiV1GenerationsJobIdRoute,
  } as any)
const ApiV1GenerationsJobIdRetryRoute =
  ApiV1GenerationsJobIdRetryRouteImport.update({
    id: '/retry',
    path: '/retry',
    getParentRoute: () => ApiV1GenerationsJobIdRoute,
  } as any)
const ApiV1GenerationsJobIdPublishRoute =
  ApiV1GenerationsJobIdPublishRouteImport.update({
    id: '/publish',
    path: '/publish',
    getParentRoute: () => ApiV1GenerationsJobIdRoute,
  } as any)
const ApiV1GenerationsJobIdNotifyRoute =
  ApiV1GenerationsJobIdNotifyRouteImport.update({
    id: '/notify',
    path: '/notify',
    getParentRoute: () => ApiV1GenerationsJobIdRoute,
  } as any)
const ApiV1GenerationsJobIdEditsRoute =
  ApiV1GenerationsJobIdEditsRouteImport.update({
    id: '/edits',
    path: '/edits',
    getParentRoute: () => ApiV1GenerationsJobIdRoute,
  } as any)
const ApiMediaHubGenerationJobIdVideoRoute =
  ApiMediaHubGenerationJobIdVideoRouteImport.update({
    id: '/api/media-hub/generation/$jobId/video',
    path: '/api/media-hub/generation/$jobId/video',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/legal/data-deletion': typeof LegalDataDeletionRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/v1/generations': typeof ApiV1GenerationsRouteWithChildren
  '/api/v1/platform-accounts': typeof ApiV1PlatformAccountsRoute
  '/generations/$jobId/edit': typeof GenerationsJobIdEditRoute
  '/oauth/instagram/callback': typeof OauthInstagramCallbackRoute
  '/oauth/youtube/callback': typeof OauthYoutubeCallbackRoute
  '/api/media-hub/uploads/reference-image': typeof ApiMediaHubUploadsReferenceImageRoute
  '/api/v1/generations/$jobId': typeof ApiV1GenerationsJobIdRouteWithChildren
  '/api/v1/prompts/optimize': typeof ApiV1PromptsOptimizeRoute
  '/api/v1/uploads/presign': typeof ApiV1UploadsPresignRoute
  '/api/media-hub/generation/$jobId/video': typeof ApiMediaHubGenerationJobIdVideoRoute
  '/api/v1/generations/$jobId/edits': typeof ApiV1GenerationsJobIdEditsRoute
  '/api/v1/generations/$jobId/notify': typeof ApiV1GenerationsJobIdNotifyRoute
  '/api/v1/generations/$jobId/publish': typeof ApiV1GenerationsJobIdPublishRoute
  '/api/v1/generations/$jobId/retry': typeof ApiV1GenerationsJobIdRetryRoute
  '/api/v1/generations/$jobId/video': typeof ApiV1GenerationsJobIdVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/legal/data-deletion': typeof LegalDataDeletionRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/v1/generations': typeof ApiV1GenerationsRouteWithChildren
  '/api/v1/platform-accounts': typeof ApiV1PlatformAccountsRoute
  '/generations/$jobId/edit': typeof GenerationsJobIdEditRoute
  '/oauth/instagram/callback': typeof OauthInstagramCallbackRoute
  '/oauth/youtube/callback': typeof OauthYoutubeCallbackRoute
  '/api/media-hub/uploads/reference-image': typeof ApiMediaHubUploadsReferenceImageRoute
  '/api/v1/generations/$jobId': typeof ApiV1GenerationsJobIdRouteWithChildren
  '/api/v1/prompts/optimize': typeof ApiV1PromptsOptimizeRoute
  '/api/v1/uploads/presign': typeof ApiV1UploadsPresignRoute
  '/api/media-hub/generation/$jobId/video': typeof ApiMediaHubGenerationJobIdVideoRoute
  '/api/v1/generations/$jobId/edits': typeof ApiV1GenerationsJobIdEditsRoute
  '/api/v1/generations/$jobId/notify': typeof ApiV1GenerationsJobIdNotifyRoute
  '/api/v1/generations/$jobId/publish': typeof ApiV1GenerationsJobIdPublishRoute
  '/api/v1/generations/$jobId/retry': typeof ApiV1GenerationsJobIdRetryRoute
  '/api/v1/generations/$jobId/video': typeof ApiV1GenerationsJobIdVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/legal/data-deletion': typeof LegalDataDeletionRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/v1/generations': typeof ApiV1GenerationsRouteWithChildren
  '/api/v1/platform-accounts': typeof ApiV1PlatformAccountsRoute
  '/generations/$jobId/edit': typeof GenerationsJobIdEditRoute
  '/oauth/instagram/callback': typeof OauthInstagramCallbackRoute
  '/oauth/youtube/callback': typeof OauthYoutubeCallbackRoute
  '/api/media-hub/uploads/reference-image': typeof ApiMediaHubUploadsReferenceImageRoute
  '/api/v1/generations/$jobId': typeof ApiV1GenerationsJobIdRouteWithChildren
  '/api/v1/prompts/optimize': typeof ApiV1PromptsOptimizeRoute
  '/api/v1/uploads/presign': typeof ApiV1UploadsPresignRoute
  '/api/media-hub/generation/$jobId/video': typeof ApiMediaHubGenerationJobIdVideoRoute
  '/api/v1/generations/$jobId/edits': typeof ApiV1GenerationsJobIdEditsRoute
  '/api/v1/generations/$jobId/notify': typeof ApiV1GenerationsJobIdNotifyRoute
  '/api/v1/generations/$jobId/publish': typeof ApiV1GenerationsJobIdPublishRoute
  '/api/v1/generations/$jobId/retry': typeof ApiV1GenerationsJobIdRetryRoute
  '/api/v1/generations/$jobId/video': typeof ApiV1GenerationsJobIdVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/api/health'
    | '/api/openapi'
    | '/legal/data-deletion'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/v1/generations'
    | '/api/v1/platform-accounts'
    | '/generations/$jobId/edit'
    | '/oauth/instagram/callback'
    | '/oauth/youtube/callback'
    | '/api/media-hub/uploads/reference-image'
    | '/api/v1/generations/$jobId'
    | '/api/v1/prompts/optimize'
    | '/api/v1/uploads/presign'
    | '/api/media-hub/generation/$jobId/video'
    | '/api/v1/generations/$jobId/edits'
    | '/api/v1/generations/$jobId/notify'
    | '/api/v1/generations/$jobId/publish'
    | '/api/v1/generations/$jobId/retry'
    | '/api/v1/generations/$jobId/video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/api/health'
    | '/api/openapi'
    | '/legal/data-deletion'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/v1/generations'
    | '/api/v1/platform-accounts'
    | '/generations/$jobId/edit'
    | '/oauth/instagram/callback'
    | '/oauth/youtube/callback'
    | '/api/media-hub/uploads/reference-image'
    | '/api/v1/generations/$jobId'
    | '/api/v1/prompts/optimize'
    | '/api/v1/uploads/presign'
    | '/api/media-hub/generation/$jobId/video'
    | '/api/v1/generations/$jobId/edits'
    | '/api/v1/generations/$jobId/notify'
    | '/api/v1/generations/$jobId/publish'
    | '/api/v1/generations/$jobId/retry'
    | '/api/v1/generations/$jobId/video'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/api/health'
    | '/api/openapi'
    | '/legal/data-deletion'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/v1/generations'
    | '/api/v1/platform-accounts'
    | '/generations/$jobId/edit'
    | '/oauth/instagram/callback'
    | '/oauth/youtube/callback'
    | '/api/media-hub/uploads/reference-image'
    | '/api/v1/generations/$jobId'
    | '/api/v1/prompts/optimize'
    | '/api/v1/uploads/presign'
    | '/api/media-hub/generation/$jobId/video'
    | '/api/v1/generations/$jobId/edits'
    | '/api/v1/generations/$jobId/notify'
    | '/api/v1/generations/$jobId/publish'
    | '/api/v1/generations/$jobId/retry'
    | '/api/v1/generations/$jobId/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiOpenapiRoute: typeof ApiOpenapiRoute
  LegalDataDeletionRoute: typeof LegalDataDeletionRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalTermsOfServiceRoute: typeof LegalTermsOfServiceRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiV1GenerationsRoute: typeof ApiV1GenerationsRouteWithChildren
  ApiV1PlatformAccountsRoute: typeof ApiV1PlatformAccountsRoute
  GenerationsJobIdEditRoute: typeof GenerationsJobIdEditRoute
  OauthInstagramCallbackRoute: typeof OauthInstagramCallbackRoute
  OauthYoutubeCallbackRoute: typeof OauthYoutubeCallbackRoute
  ApiMediaHubUploadsReferenceImageRoute: typeof ApiMediaHubUploadsReferenceImageRoute
  ApiV1PromptsOptimizeRoute: typeof ApiV1PromptsOptimizeRoute
  ApiV1UploadsPresignRoute: typeof ApiV1UploadsPresignRoute
  ApiMediaHubGenerationJobIdVideoRoute: typeof ApiMediaHubGenerationJobIdVideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms-of-service': {
      id: '/legal/terms-of-service'
      path: '/legal/terms-of-service'
      fullPath: '/legal/terms-of-service'
      preLoaderRoute: typeof LegalTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/data-deletion': {
      id: '/legal/data-deletion'
      path: '/legal/data-deletion'
      fullPath: '/legal/data-deletion'
      preLoaderRoute: typeof LegalDataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi': {
      id: '/api/openapi'
      path: '/api/openapi'
      fullPath: '/api/openapi'
      preLoaderRoute: typeof ApiOpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/youtube/callback': {
      id: '/oauth/youtube/callback'
      path: '/oauth/youtube/callback'
      fullPath: '/oauth/youtube/callback'
      preLoaderRoute: typeof OauthYoutubeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/instagram/callback': {
      id: '/oauth/instagram/callback'
      path: '/oauth/instagram/callback'
      fullPath: '/oauth/instagram/callback'
      preLoaderRoute: typeof OauthInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generations/$jobId/edit': {
      id: '/generations/$jobId/edit'
      path: '/generations/$jobId/edit'
      fullPath: '/generations/$jobId/edit'
      preLoaderRoute: typeof GenerationsJobIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/platform-accounts': {
      id: '/api/v1/platform-accounts'
      path: '/api/v1/platform-accounts'
      fullPath: '/api/v1/platform-accounts'
      preLoaderRoute: typeof ApiV1PlatformAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/generations': {
      id: '/api/v1/generations'
      path: '/api/v1/generations'
      fullPath: '/api/v1/generations'
      preLoaderRoute: typeof ApiV1GenerationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/uploads/presign': {
      id: '/api/v1/uploads/presign'
      path: '/api/v1/uploads/presign'
      fullPath: '/api/v1/uploads/presign'
      preLoaderRoute: typeof ApiV1UploadsPresignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/prompts/optimize': {
      id: '/api/v1/prompts/optimize'
      path: '/api/v1/prompts/optimize'
      fullPath: '/api/v1/prompts/optimize'
      preLoaderRoute: typeof ApiV1PromptsOptimizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/generations/$jobId': {
      id: '/api/v1/generations/$jobId'
      path: '/$jobId'
      fullPath: '/api/v1/generations/$jobId'
      preLoaderRoute: typeof ApiV1GenerationsJobIdRouteImport
      parentRoute: typeof ApiV1GenerationsRoute
    }
    '/api/media-hub/uploads/reference-image': {
      id: '/api/media-hub/uploads/reference-image'
      path: '/api/media-hub/uploads/reference-image'
      fullPath: '/api/media-hub/uploads/reference-image'
      preLoaderRoute: typeof ApiMediaHubUploadsReferenceImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/generations/$jobId/video': {
      id: '/api/v1/generations/$jobId/video'
      path: '/video'
      fullPath: '/api/v1/generations/$jobId/video'
      preLoaderRoute: typeof ApiV1GenerationsJobIdVideoRouteImport
      parentRoute: typeof ApiV1GenerationsJobIdRoute
    }
    '/api/v1/generations/$jobId/retry': {
      id: '/api/v1/generations/$jobId/retry'
      path: '/retry'
      fullPath: '/api/v1/generations/$jobId/retry'
      preLoaderRoute: typeof ApiV1GenerationsJobIdRetryRouteImport
      parentRoute: typeof ApiV1GenerationsJobIdRoute
    }
    '/api/v1/generations/$jobId/publish': {
      id: '/api/v1/generations/$jobId/publish'
      path: '/publish'
      fullPath: '/api/v1/generations/$jobId/publish'
      preLoaderRoute: typeof ApiV1GenerationsJobIdPublishRouteImport
      parentRoute: typeof ApiV1GenerationsJobIdRoute
    }
    '/api/v1/generations/$jobId/notify': {
      id: '/api/v1/generations/$jobId/notify'
      path: '/notify'
      fullPath: '/api/v1/generations/$jobId/notify'
      preLoaderRoute: typeof ApiV1GenerationsJobIdNotifyRouteImport
      parentRoute: typeof ApiV1GenerationsJobIdRoute
    }
    '/api/v1/generations/$jobId/edits': {
      id: '/api/v1/generations/$jobId/edits'
      path: '/edits'
      fullPath: '/api/v1/generations/$jobId/edits'
      preLoaderRoute: typeof ApiV1GenerationsJobIdEditsRouteImport
      parentRoute: typeof ApiV1GenerationsJobIdRoute
    }
    '/api/media-hub/generation/$jobId/video': {
      id: '/api/media-hub/generation/$jobId/video'
      path: '/api/media-hub/generation/$jobId/video'
      fullPath: '/api/media-hub/generation/$jobId/video'
      preLoaderRoute: typeof ApiMediaHubGenerationJobIdVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiV1GenerationsJobIdRouteChildren {
  ApiV1GenerationsJobIdEditsRoute: typeof ApiV1GenerationsJobIdEditsRoute
  ApiV1GenerationsJobIdNotifyRoute: typeof ApiV1GenerationsJobIdNotifyRoute
  ApiV1GenerationsJobIdPublishRoute: typeof ApiV1GenerationsJobIdPublishRoute
  ApiV1GenerationsJobIdRetryRoute: typeof ApiV1GenerationsJobIdRetryRoute
  ApiV1GenerationsJobIdVideoRoute: typeof ApiV1GenerationsJobIdVideoRoute
}

const ApiV1GenerationsJobIdRouteChildren: ApiV1GenerationsJobIdRouteChildren = {
  ApiV1GenerationsJobIdEditsRoute: ApiV1GenerationsJobIdEditsRoute,
  ApiV1GenerationsJobIdNotifyRoute: ApiV1GenerationsJobIdNotifyRoute,
  ApiV1GenerationsJobIdPublishRoute: ApiV1GenerationsJobIdPublishRoute,
  ApiV1GenerationsJobIdRetryRoute: ApiV1GenerationsJobIdRetryRoute,
  ApiV1GenerationsJobIdVideoRoute: ApiV1GenerationsJobIdVideoRoute,
}

const ApiV1GenerationsJobIdRouteWithChildren =
  ApiV1GenerationsJobIdRoute._addFileChildren(
    ApiV1GenerationsJobIdRouteChildren,
  )

interface ApiV1GenerationsRouteChildren {
  ApiV1GenerationsJobIdRoute: typeof ApiV1GenerationsJobIdRouteWithChildren
}

const ApiV1GenerationsRouteChildren: ApiV1GenerationsRouteChildren = {
  ApiV1GenerationsJobIdRoute: ApiV1GenerationsJobIdRouteWithChildren,
}

const ApiV1GenerationsRouteWithChildren =
  ApiV1GenerationsRoute._addFileChildren(ApiV1GenerationsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiOpenapiRoute: ApiOpenapiRoute,
  LegalDataDeletionRoute: LegalDataDeletionRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalTermsOfServiceRoute: LegalTermsOfServiceRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiV1GenerationsRoute: ApiV1GenerationsRouteWithChildren,
  ApiV1PlatformAccountsRoute: ApiV1PlatformAccountsRoute,
  GenerationsJobIdEditRoute: GenerationsJobIdEditRoute,
  OauthInstagramCallbackRoute: OauthInstagramCallbackRoute,
  OauthYoutubeCallbackRoute: OauthYoutubeCallbackRoute,
  ApiMediaHubUploadsReferenceImageRoute: ApiMediaHubUploadsReferenceImageRoute,
  ApiV1PromptsOptimizeRoute: ApiV1PromptsOptimizeRoute,
  ApiV1UploadsPresignRoute: ApiV1UploadsPresignRoute,
  ApiMediaHubGenerationJobIdVideoRoute: ApiMediaHubGenerationJobIdVideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
